### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by opsb** [toranb/ember-redux#11]
Hey @toranb, the integration looks great so far! Have you given any thought to how validations might work? 

They could perhaps just be handled on the component, using https://github.com/DockYard/ember-validations. An action handler on a presenter component could take care of the validation before dispatching a closure action. While the ember-validations approach seems practical I'm not sure how it fits in with redux or CQRS (I've found CQRS to have clearer definitions of the responsibilities than redux - http://jaysoo.ca/2015/02/06/what-the-flux/). 

edit: took closure actions into account

**Comment by toranb** [comment]
Good question! Right now I'm just doing component level validation (on purpose) because each component has a unique context/ or perspective. And because the mapped values from redux are just computed properties it should work/ act like normal ember.

For async validation a you can fire them from with the components actions mapping and you have a reference to anything you'd need to display feedback from the user. I'll throw up a short example tonight when I'm back in town to express the second half of my example (doing a full day of travel without wifi)

**Comment by toranb** [comment]
'''js
var mapDispatchToActions = {
  return {
    add: function() {
      var component = this;
      ajax("api/users", "GET").then((response) => {
        console.log(component.get("number"));
        //or dispatch({type: "ADD"});
      });
    }
  }
};

**Comment by opsb** [comment]
Ah, I hadn't realised `this` pointed to the component. I'd have to check but I presume `this` would always point to the container component rather than the component where the action originated(where I'd want to handle the validation error). Closure actions seem to solve this one though. If you invoke a closure action from a normal action within a presenter component then it can return a promise and raise an error to indicate that creation of the action was rejected (e.g. when remote validation fails).

**Comment by toranb** [comment]
Right on - closure actions have solved this problem for me so far but let me know if you find anything else that we should add to support better validation in components generally.
