### ISSUE TITLE
Access to ember's container for Action creators

### ISSUE THREAD

**Issue by opsb** [toranb/ember-redux#12]
My app makes use of phoenix channels (over a websocket) and needs to manage subscribing/dispatching to them. Typically with redux you'd use Action Creators to manage async operations, dispatching actions to the reducer at the appropriate times. These Action Creators are shared between components to allow the use of common business logic / resources. 

With ember-redux `dispatchToActions` fills the role of the Action Creators. Because it's just a function there's nothing to stop you importing a map of ActionCreators that's shared across the entire app. One limitation though is that it doesn't have access to ember's container. Ember's container seems like the natural place to keep track of things like websockets, channel subscriptions etc. so this would be a useful addition. 

I see a few options here:
1) Simply expose the ember container with `dispatchToActions(dispatch, container)`
2) Move the dispatcher into the ember container and use a convention for registering actions e.g.

```
// /app/actions/todos
export default Ember.Actions.extend({
  channels: inject.service('channels'),
  dispatch: inject.service('dispatch'),

  addTodo(name) {
    let {dispatch, channels} = this.getProperties('dispatch', 'channels');
    let todoId = uuid();
    dispatch({type: 'ADD_TODO_REQUESTED', todoId});
    channels.get('todos').add(name)
      .receive('ok', resp => dispatch({type: 'ADD_TODO_COMPLETED', todoId}))
      .receive('error', resp => dispatch({type: 'ADD_TODO_FAILED', todoId})
  }
});
```

(2) could potentially just be built on top of (1) so perhaps that would be a good place to start.

There's most likely other approaches here and I'd be very happy to discuss them. If we can come to a consensus then I should have time to put a PR together this week.

**Comment by opsb** [comment]
It occurred to me that I could just use standard ember services to handle action creation (rather than redux-thunk) e.g.

```
// app/services/todos.js
export default Ember.Service.extend({
  redux: inject.service('redux'),
  channels: inject.service('channels'),

  add(name) {
    let {redux, channels} = this.getProperties('redux', 'channels');
    let todoId = uuid();
    redux.dispatch({type: 'ADD_TODO_REQUESTED', todoId});
    channels.get('todos').add(name)
      .receive('ok', resp => redux.dispatch({type: 'ADD_TODO_COMPLETED', todoId}))
      .receive('error', resp => redux.dispatch({type: 'ADD_TODO_FAILED', todoId});
  }
});
```

This service can then be injected into a component meaning the component would be completely ignorant of redux. 

I'm new to redux so I'd be interested to hear what other people using ember-redux think about this and how it compares to using redux-thunk.

**Comment by toranb** [comment]
@opsb your opening definition of actions creators `Typically with redux you'd use Action Creators to manage async operations, dispatching actions to the reducer at the appropriate times` isn't what I've come to know as the default definition. I've always heard from Dan that Action Creators are used to reduce `boilerplate` when you use the same action over and over in your application

> It is another common convention that, instead of creating action objects inline in the places where you dispatch the actions, you would create functions generating them.

http://redux.js.org/docs/recipes/ReducingBoilerplate.html

In your second comment I noticed you asking more about async actions (and comparing a service vs redux-thunk). I actually included redux-thunk in this library because I felt you simply could not ship without async action support and it's basically the defacto :)

I'm not doing any work with web sockets at the moment but I'm using plenty of async actions with XHR that look something like this.

```js
var dispatchToActions = (dispatch) => {
  return {
    remove: (id) => ajax(`/api/users/${id}`, 'DELETE').then(() => dispatch({type: 'REMOVE_USER', id: id}))
  };
};
```

I really liked your example service above and so much that I wanted to see if you could submit a PR to the documentation (gh-pages branch of this project) labeled "reducing boilerplate" (starting with a title of Action Creators) where you go into detail about your solution. I really think this shows an awesome way to encapsulate more involved async actions with redux and ember :)

**Comment by opsb** [comment]
> I've always heard from Dan that Action Creators are used to reduce boilerplate when you use the same action over and over in your application

@toranb it does seem that there's some different takes on this, I found this thread really useful for comparing different approaches https://github.com/reactjs/redux/issues/891. I'm coming at it from the CQRS perspective so that's probably what leads me to the interpretation:

> Typically with redux you'd use Action Creators to manage async operations, dispatching actions to the reducer at the appropriate times.

Anyway, it seems that the different approaches are all accommodated so each project can make their own call on that one.

I'm glad you like the service example, I'll try and PR the gh-pages this week. Thanks again for your work getting this going!

**Comment by toranb** [comment]
@opsb awesome! thanks for helping contribute to the docs/ community !!!
