### ISSUE TITLE
Consider exploding args in the route.js function

### ISSUE THREAD

**Issue by foxnewsnetwork** [toranb/ember-redux#17]
Background
===
In your code at https://github.com/toranb/ember-redux/blob/master/addon/route.js#L12 we see:

```javascript
route[func] = function(args) {
  return funcs[func](redux.dispatch.bind(redux), args);
};
```

Notably, the `args` param only captures the first parameter of whatever native `Ember.Route` method we're declaring. Consider making the following changes:

Suggested Changes
===
```javascript
route[func] = function(...args) {
  args.unshift(redux.dispatch.bind(redux));
  return funcs[func].apply(route, args);
};
```

Reasoning
===
`Ember.Route` methods such as `beforeModel`, `afterModel`, etc., all get passed not only the model, but also the transition, and other such possible parameters. Properly passing those parameters in may be useful for users.

Questions
===
Q: What do you think? If you're okay with it, I'll can do a PR when I get off of work

Q: Why not also pass in `redux.subscribe`? Is using `subscribe` in the route not recommend?

Notes
===
Thanks for your guidance in the slack chat the other day, I looked into redux-saga and it seems more and more that's the way we'll wind up going with.

**Comment by toranb** [comment]
@foxnewsnetwork wow! I truly assumed that I was actually passing all the arguments through but as you pointed out ... clearly not :)

I view this behavior as a bug honestly - it was not my intention to alter the contract or arguments of a route in any way (as ember developers should expect everything they would get normally w/ the addition of dispatch).

Regarding subscribe - I'd like to leave that out to ensure we only have 1 place for the developer to register for callbacks. The connect api for components is the place to listen for changes/ re-render. In ember I've always felt the role of the router was simply to fetch data given some url

I'd welcome a pull request if you've got time to show it in action. You'll notice I usually prefer a higher level test but if you find that difficult to pull off just write something at the unit level (I was able to write a failing test myself just now using setupController because the 3rd argument is undefined (not the model as you'd expect) so anything you'd normally do in that method using classic ember would fall down quickly as you might imagine)

Thanks for hearing me out on slack and deciding to take the addon for a spin :)

**Comment by toranb** [comment]
Thanks again - your PR getting merged now closes this out :)
