### ISSUE TITLE
Improvement: add support for store enhancers

### ISSUE THREAD

**Issue by Eptis** [toranb/ember-redux#2]
I didn't see a place in the addon where you can define store enhancers which are useful for connecting with the Redux Devtools that are out there.

If you are open to adding support for this, I think something like this might work:

***/services/redux.js***

```
import Ember from 'ember';
import redux from 'npm:redux';
import reducers from '../reducers/index';
import optional from '../reducers/optional';
import enhancers from '../enhancers/index';
import middleware from '../middleware/index';

var { createStore, applyMiddleware, combineReducers, compose } = redux;
var createStoreWithMiddleware = compose(
  applyMiddleware(...middleware),
  enhancers
)(createStore);

```

***/enhancers/index.js***

```
import redux from 'npm:redux';
import devToolsExt from './devToolsExt'

export default redux.compose(devToolsExt);
```

***/enhancers/devToolsExt*** *(Redux devtools chrome extension as an example)*

```
var devToolsExt = window.devToolsExtension ? window.devToolsExtension() : f => f

export default devToolsExt;
```

**Comment by toranb** [comment]
I actually added an extension just for this :)

app/reducers/optional.js

Here it is in action (full working time travel example). It's not pretty yet but I'm building out something that will be its own addon in the next few weeks/months

https://github.com/toranb/ember-redux-example/commit/f5e61f0a5300f6647ec8fbfc60e6e26fc3afda28

**Comment by toranb** [comment]
I'll take a look at this enhancers + chrome setup you mentioned. I didn't realize chrome had epic tooling already to go (bonus if I'm not required to write anything and it "just works")

**Comment by toranb** [comment]
I'm looking into this tonight so I'll provide some much needed feedback on dev tooling

**Comment by toranb** [comment]
@Eptis wow it was *just* that simple! This is actually awesome because now I don't need to reinvent the wheel and both ember/angular/react users can all benefit from the same "core" time travel component (baked into chrome dev tools).

The only question now (with this default set of tooling) - how should we deal with route transitions? That was the last big question on my "todo list" as I was building this library (and didn't have many people to bounce the ideas off).

A few months back I looked at this react project that helps keep the "router in sync" with redux but I wasn't sure how it worked in practice / what the user experience should be for "stepping back" (when a route transition or 2 have occurred).

Have you seen this done well? If so how would this scenario play out?

1) visit route /users

a) route transition occurs
b) redux action returns a new state w/ some users

2) go into details route from a link-to

a) route transition occurs
b) redux action returns a new state with a single "selected" user (also this user would be present in the "all" users array returned)

3) you decide to update some attributes on the user model

*no route transition
a) redux action returns a new state w/ new attrs for that user

4) click some other high navigation item

a) route transition occurs
b) redux action fires/returns some new state without touching users

** **

now- you decide to "time travel" with the devtools and you want to rollback to state 3 (above) - how/when does the "transition" in step 4 get rolled back? I assume we would need to hack/reopen the route and "didTransition" would/could fire to redux (helping keep the state in sync so rollbacks would be an option). Even with such a hack I assume we would need to write some custom code/or a custom time travel step to "transition back" correctly within ember

thoughts ?

**Comment by toranb** [comment]
@Eptis another question quick - I assume we will do something like "middleware" by making "enhancers" optional - you just add one to the service (app/enhancers/index.js) and away you go. Mostly as a config option/override for dev only /or opt-in staging debug support

If that sounds good I can test drive it/ ship this in v1.1.0 or something this week or weekend. I think adding this is a great idea but I still want to think through the rollback scenario above (and how it should work with a route in ember).

**Comment by toranb** [comment]
@Eptis just pushed up support for enhancers - I'm planning a v1.1.0 release this weekend pending some more thought. I'd like to think through this a bit before making it a public api but at this time it looks legit

https://github.com/toranb/ember-redux/commit/602cce7bab56105f61ca2d10bbb34a2c8c7c1446

**Comment by toranb** [comment]
@Eptis here is a real example ember app showing the dev tools setup you mentioned above. It's really easy to use this and I'll plan some docs for the jekyll site once we confirm this is solid

https://github.com/toranb/ember-redux-example/commit/9e9166d992b926b88ac8e96ac231bca24d4def61

**Comment by Eptis** [comment]
This is something I have been thing about as well. I think the state changes should be performed from `didTransition`

I was looking at [redux-router](https://github.com/acdlite/redux-router) myself and they list this as features which I think is what similar to what the support should be:

- Keep your router state inside your Redux Store.
- Interact with the Router with the same API you use to interact with the rest of your app state.
- Completely interoperable with existing React Router API. <Link />, router.transitionTo(), etc. still work.
- Serialize and deserialize router state.
- Works with time travel feature of Redux Devtools!

I do think for Ember this is a difficult one, as the router is seen as the place where you keep track of these state changes, however I think a mechanism that pulls the state changes (query params, current-path etc) when a transition occurs and sends them as an action to the store would be a reasonable approach.

The only thing I don't really know how to figure out if you "pop" a state change from the timeline and its a route change. It should transition back, but it should not trigger the sending of other actions (from the `model` hook for example). Do you have any ideas about this?

**Comment by Eptis** [comment]
And the enhancers implementation is :+1:

**Comment by toranb** [comment]
@Eptis I like the discussion here and think we should open another issue to track the `didTransition` feature. I'll get a release for the enhancers out this weekend - thanks again for submitting this!
