### ISSUE TITLE
Multiple sets of reducers?

### ISSUE THREAD

**Issue by dbashford** [toranb/ember-redux#27]
We've taken the approach of breaking small pieces of our product up and isolating them in addons.  Each addon is its own little self-contained thing, usually a bundle of 10-20 components, often reused all over the application.

Recently converted one of those addons to use ember-redux (worked like a charm!).  Incorporated that addon into our main project and it all works great. ember-redux, running in the main app, has no problem finding the reducers from the addon.

Now starting to look and see what it'll take to start converting big chunks of the main project, pieces not isolated in addons.  As soon as I added a reducers folder/`index.js` to the primary Ember app, ember-redux no longer located the addon's reducers.

This was easily solved by importing the `addonNameHere/reducers/index` and re-exporting it from `mainProject/reducers/index`.

Might be nice, though, if it was able to track down the reducers from all candidate locations and `combineReducers` them all together?

Talkin' crazy?

**Comment by dbashford** [comment]
Worth mentioning, this may all be doable already and there's something about wiring the addon into the main app that I'm not getting right.

There's always a good deal of Ember magic involved, this may be the domain of the resolver? Something magical must be happening for it to have found the addon's reducers and then not have found them when something better came along.

**Comment by toranb** [comment]
@dbashford first up - awesome to hear adopting this has been successful in your apps/addons! I'm always amazed when I hear someone else is using this project and dare I say "loving it" :)

About the app/addon `reducers/index.js` overlap, I think adding first-class support for `reducers` is the most correct solution to solve your pain point. I'm glad you found a not so terrible work around for the moment, but I do appreciate you calling out the bigger issue here (to me it's making the reducer type something ember is aware of / doing a better job in ember-redux of allowing a true combine step).

I'll need to seek out some ember-cli help on this to better understand how we can organize/setup the reducer folder. I'm curious on your feedback here -one solution could be to not have an explicit index and instead just "automagically" combine all *.js files found in each reducers folder (exporting them from here instead).

On the one hand, I'm also waiting to hear how the recently merged RFC for "module unification" will play out in this scenario (I realize it's not yet supported but because it was merged this week I'm due to refresh myself on the changes coming).

**Comment by aaminev** [comment]
hey guys! so overlapping also applies to middleware and enhancers, both folders contain index.js.

all of those things can require particular order, for example: 
- https://github.com/evgenyrodionov/redux-logger must be the last middleware, 
- final reducers composition may encounter same key conflicts if all reducers are just "automagically" combined as js files.

also store creation itself sometimes needs more control and may be custom.

so what if we use redux itself as a first class citizen by putting store creation (with all reducers/middleware/enhancers) into engineer's hands and give an API to provide the store to ember-redux? 

as example - react-redux:
```js
<Provider store={store}>
    <App />
</Provider>
```
where provider basically does the same thing as redux service in this project, except store is passed as param.

**Comment by toranb** [comment]
@aaminev I've thought about exposing a createStore override so people with more advanced used cases can opt out of the default. A backwards compatible way to do this now is that we import a createStore.js file from the app/ use that inside the service on init

https://github.com/toranb/ember-redux/blob/master/app/services/redux.js#L27

**Comment by toranb** [comment]
@aaminev about the provider api (used in react-redux) => I'm not certain what this would look like in ember myself but I'm open to suggestions. Also- it's very important for now that the library remain backwards compatible (meaning we need to consider everyone using the 1x series today). I don't plan to release a 2x of the addon any earlier than March 2017 to assure people that we are a library (and ecosystem) about stability /not churn.

I was happy to see that the react-redux v5 (beta) release coming soon isn't an api breaking change. In fact, it appears mostly additive from the consumers standpoint. This should further enable us to remain react-redux compatible/friendly (allowing ember developers to get even more comfortable with the redux idioms/ approach by removing the fear of change that is often present in new(er) tech)

**Comment by aaminev** [comment]
@toranb what if we had a service that we can use to extend from and to create our own. 

For example now if I create `app/services/redux.js`, app won't call addon's service because of how ember-cli works. So currently I can implement my own redux service with my own store creation, and as long as it has the same interface as addon's service, everything will work fine. What I could use to be always compatible with ember-redux addon is a base service from ember-redux, and do something like this in my own redux service:
```js
import BaseService from 'ember-redux/services/redux';
const myStore = ...
export default BaseService.extend({
    init() {
        this.store = myStore; // or through API, like this.setStore(myStore);
        this._super(...arguments);
    },
});
```

this could allow us to implement advanced use cases and be backward compatible with current version.

**Comment by toranb** [comment]
@aaminev I'm in favor of extension but I'd prefer composition rather than forcing the user to inherit from a base service. Would you be open to something like the below? If yes, could you work up a PR showing how you'd prefer to override this functionality?

https://github.com/toranb/ember-redux/commit/c87026c6e34a4fa62a96fe5a56b4bf0284a3cbc0

**Comment by toranb** [comment]
@aaminev I've got plans to open this up for extension in the future and if nothing else I can start a pull request in the coming month or so to unlock advanced store configuration. I'm planning to close this issue for now. If you want to take a run at the pull request for this in the future please feel free.

@dbashford I feel this issue has gotten away from the core discussion you started with almost a month ago. If you still want to discuss it in more detail please open a new issue so we can stay on topic :)
