### ISSUE TITLE
Return dispatch return value from service?

### ISSUE THREAD

**Issue by brettburley** [toranb/ember-redux#5]
When using the `redux-thunk` middleware, I've created some action creators with routes that look like:
```javascript
import Ember from 'ember';
import route from 'ember-redux/route';

function loadData(id) {
  return async function (dispatch) {
    const data = await fetch(...);
    dispatch({ type: 'DESERIALIZE_DATA', data: data });
  }
}

export default route({
  model(dispatch, params) {
    return dispatch(loadData(params.id));
  }
})(Ember.Route.extend());
```

However, since the dispatch method on the service (https://github.com/toranb/ember-redux/blob/master/app/services/redux.js#L20) just returns undefined, the ember model loading hooks don't wait for the async action to complete before rendering the route.

Are there any downsides to modifying `dispatch` on the service to always return the dispatch result? The only consideration I can think of right now is potentially returning a value in the model hook, which would cause Ember to setup a model on the controller. However, so long that you don't `return` dispatch from the model *unless* it's a promise from thunk, it seems like we can avoid inadvertently returning a model.

**Comment by toranb** [comment]
This is a good catch - I just realized I don't have any examples/tests that use this pattern in the addon. To add this I'd just like a legit example (codified as a test case w/ acceptance) just so others who follow can see it in action.

In the above I see you are using fetch but I'm not sure what ember addon/npm module you are using. Would you be up to add a component/route/acceptance test here that shows it off? 

One other question about your example - in the `loadData` function I see you return `async` function but inside that function you simply `dispatch` but does this need to be `return dispatch` instead?

If you can create a full example app (instead of the acceptance test) I could take that working example and test drive this feature. Just let me know how you prefer to operate going forward

**Comment by brettburley** [comment]
Ah yes, I was just using `fetch` as an example of something that returns a promise:
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

Regarding calling `dispatch` vs. returning it, I think I *don't* actually want to return it, because if I do, I would expect Ember will use that resolved promise value as the `model`. By not returning it, the promise resolves with `undefined`, and therefore we don't get any unnecessary `model` attached to the controller.

**Comment by brettburley** [comment]
Closing this in favor of PR https://github.com/toranb/ember-redux/issues/7.
